/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ParseForm {
    }
}
declare global {
    interface HTMLParseFormElement extends Components.ParseForm, HTMLStencilElement {
    }
    var HTMLParseFormElement: {
        prototype: HTMLParseFormElement;
        new (): HTMLParseFormElement;
    };
    interface HTMLElementTagNameMap {
        "parse-form": HTMLParseFormElement;
    }
}
declare namespace LocalJSX {
    interface ParseForm {
    }
    interface IntrinsicElements {
        "parse-form": ParseForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "parse-form": LocalJSX.ParseForm & JSXBase.HTMLAttributes<HTMLParseFormElement>;
        }
    }
}
